### ISSUE TITLE
Can't install package because dependency Taxonstand not available

### ISSUE THREAD

**Issue by egouldo** [LimaRAF/plantR#104]
`Taxonstand::` has been removed from CRAN as per https://cran.r-project.org/web/packages/Taxonstand/index.html on  2023-12-15. Because `Taxonstand` is listed as dependency, `plantR::` cannot be installed. See repress below.

*Local `.Rprofile` detected at `/Users/elliotgould/Documents/GitHub/VEFMAP_VEG_Stage6/.Rprofile`*

``` r
library("remotes")
install_github("LimaRAF/plantR")
#> Using github PAT from envvar GITHUB_PAT. Use `gitcreds::gitcreds_set()` and unset GITHUB_PAT in .Renviron (or elsewhere) if you want to use the more secure git credential store instead.
#> Downloading GitHub repo LimaRAF/plantR@HEAD
#> Skipping 1 packages not available: Taxonstand
#> ── R CMD build ─────────────────────────────────────────────────────────────────
#> * checking for file ‘/private/var/folders/p7/hfv_wt9x6kl7bk4jtr1q2gk80000gn/T/RtmpvbsRyp/remotes451148a3cb74/LimaRAF-plantR-93411bb/DESCRIPTION’ ... OK
#> * preparing ‘plantR’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> Removed empty directory ‘plantR/data-raw’
#> * building ‘plantR_0.1.6.tar.gz’
#> Installing package into '/Users/elliotgould/Library/Caches/org.R-project.R/R/renv/library/VEFMAP_VEG_Stage6-1eefb234/R-4.3/aarch64-apple-darwin20'
#> (as 'lib' is unspecified)
#> Warning in i.p(...): installation of package
#> '/var/folders/p7/hfv_wt9x6kl7bk4jtr1q2gk80000gn/T//RtmpvbsRyp/file4511798251ed/plantR_0.1.6.tar.gz'
#> had non-zero exit status
```

<sup>Created on 2024-04-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Suggest the following:

- replacing dependency with [WorldFlora](https://cran.r-project.org/web/packages/WorldFlora/index.html), as suggested by `Taxonstand::` author
- Using alt version of `Taxonstand::`, `U.Taxonstand::`, https://github.com/ecoinfor/U.Taxonstand, see citation: https://pubmed.ncbi.nlm.nih.gov/36876314/

**Comment by LimaRAF** [comment]
Dear @egouldo ,

Thanks for the issue. Yes, we currently have no global-level alternative to check species names within `plantR`. This is something that I am aware for quite sometime now, but I had no time to implement. I am particularly searching for packages that can do the checking that do not need an API key or to download the entire taxonomic backbone.

Meanwhile, you can still install the package by downloading an old version of `Taxonstand` [here](https://cran.r-project.org/src/contrib/Archive/Taxonstand/) and install manually the Package Archive File (.zip or .tar.zip). `plantR` should install normally after that.

Best!

**Comment by egouldo** [comment]
Thanks @LimaRAF !

Great suggestion for the `Taxonstand` install workaround. I'll give that a go. 

Good luck finding an alternative implementation in the meantime 🙂

**Comment by jaum20** [comment]
you cant also install using `remotes`

`remotes::install_github("cran/Taxonstand")`

**Comment by egouldo** [comment]
Thank you @jaum20 !

**Comment by LimaRAF** [comment]
I removed all dependencies to Taxonstand and I am working on a solution to check species names with plantR based on user selected backbones stored elsewhere. 

Meanwhile, please use `remotes::install_github("LimaRAF/plantR", ref = "dev")` to get this new version 0.1.7 of the package which will not return this error anymore. Please re-open this issue if you still face any issues.

**Comment by egouldo** [comment]
Fantastic, thank you!
