### ISSUE TITLE
(dev branch) formatTax does not return suggestedName without scientificNameAuthorship column

### ISSUE THREAD

**Issue by ggrittz** [LimaRAF/plantR#109]
Reproducible example below:

```
Mock up data
sp_list <- c("Oreodaphne porosa", 
             "Oreodaphne porosa", 
             "Ocotea porosa", 
             "Ocotea porosa")
aut_list <- c("", 
              "Nees & Mart.",
              "",
              "(Nees & Mart.) Barroso")

df <- data.frame(scientificName = sp_list,
                 scientificNameAuthorship = aut_list)

# Running formatTax with the new plantRdata package
test_format <- plantR::formatTax(tax = df,
                          tax.name = "scientificName",
                          author.name = "scientificNameAuthorship",
                          db = plantRdata::wcvpNames)

# Running prepSpecies with the new plantRdata package
test_prep <- plantR::prepSpecies(x = df,
                              tax.names = c("scientificName",
                                            "scientificNameAuthorship"),
                              db = plantRdata::wcvpNames)
```

Outputs can be seen below:

`formatTax`
![image](https://github.com/user-attachments/assets/0ce18ba1-ab27-47e1-8033-b4957988ed85)

`prepSpecies`
![image](https://github.com/user-attachments/assets/1252bd60-e737-4c0d-aedd-7e7cc9ea4f6c)

As can be seen, `formatTax`, needs the input of `test_format$scientificNameAuthorship` to find the accepted name, while `prepSpecies` does not.

**Comment by ggrittz** [comment]
I noticed this may be due to ```use.authors```? If ```use.authors=FALSE```the names can be found.

**Comment by LimaRAF** [comment]
I just rerun this example again after some other main improvements in the function and everything seems to be ok now. Please let me know if you encounter some other issue related to this.
