### ISSUE TITLE
fixLoc replacement error when scrap = TRUE

### ISSUE THREAD

**Issue by ggrittz** [LimaRAF/plantR#110]
I'm trying to run ```plantR::fixLoc``` on a small data set (only two rows) and I get the following error:

```
Error in `[<-.data.frame`(`*tmp*`, , "municipality", value = c("colinas do sul",  : 
  replacement has 4 rows, data has 2
```

The error occurs in this step of the function

```
# Replacing missing counties
    if (any(c("municipality", "county") %in% loc.levels)) {
      # priority 1: localities specifying a county name
      x1[, "municipality"][is.na(x1[, "municipality"]) & !is.na(n4.2)] <-
        gsub("^ | $", "", n4.2[is.na(x1[, "municipality"]) & !is.na(n4.2)], perl = TRUE)
      # priority 2: first part of the locality description
      x1[, "municipality"][is.na(x1[, "municipality"]) & is.na(n4.2)] <-
        gsub("^ | $", "", n4.2.1[is.na(x1[, "municipality"]) & is.na(n4.2)], perl = TRUE)
    }
```

This part
```
x1[, "municipality"][is.na(x1[, "municipality"]) & !is.na(n4.2)]
```
equals ```character(0)```
and the object ```n4.2``` is a vector of ```NA``` with size four

I imagine the issue arises here:

```
# Spliting the locality vector to find missing information
    n4 <- strsplit(x1[ ,"locality"], ",|\\.|:|\\(|\\)|;", perl = TRUE)
    n4 <- sapply(n4, function(x) gsub("^ | $", "", x, perl = TRUE))
    
    # trying to get missing counties from the locality description (e.g. "Pico das Almas, municipio de Rio de Contas")
    n4.2 <- as.character(sapply(n4, function(x)
      paste(unique(gsub("^ | $", "",
                        x[grepl("municipio|municipality|county|provincia|village", x, perl = TRUE)], perl = TRUE
      )), collapse = "|")))
    n4.2 <- gsub("^ | $", "", n4.2, perl = TRUE)
    n4.2 <- gsub("municipio de |municipality of |municipio do |^county of |^provincia de|^provincia of|village of",
                 "",
                 n4.2, perl = TRUE)
    n4.2 <- gsub("municipio |municipality |^county |^provincia |village ",
                 "",
                 n4.2, perl = TRUE)
    n4.2[n4.2 %in% ""] <- NA
```

Since ```strsplit``` returns a vector of size four with "" only, this vector is substituted by four NA that cannot replace the values in the input df.

I am attaching the sample df as a .csv
[fixLoc_plantR.csv](https://github.com/user-attachments/files/16589716/fixLoc_plantR.csv)
 file

**Comment by LimaRAF** [comment]
Thanks @ggrittz for pointing out this problem.

I added a quick fix to avoid the issue reported (see [this commit](https://github.com/LimaRAF/plantR/commit/0d6722cd8069902ec75251c5034aea8ee756cea5)). Probably not the best that could be done to fix the problem at its root, but should solve the error reported.

Please reinstall ```plantR``` from the 'dev' branch and test it again. If it works out fine for you too, please let me know so I can close this issue.

**Comment by ggrittz** [comment]
It is working now, thank you!
