### ISSUE TITLE
fixAuthors issue with duplicated epithet + post-rank name

### ISSUE THREAD

**Issue by ggrittz** [LimaRAF/plantR#111]
When the epithet and the post-rank name (eg. Aesculus glabra var. glabra) are the same, the function considers the post-rank name to be part of the author name even if there is an actual author name after the post-rank name.

Some examples below:

```
# For the sake of reproducibility I am adding an example for each rank ('var.', 'subsp.', 'f.', 'forma')
> plantR::fixAuthors(c("Actinostemon concolor var. microphyllus Müll.Arg.",
                      "Aesculus glabra var. glabra",
                      "Comarostaphylis polifolia subsp. polifolia",
                      "Carya ovata subsp. ovata (Mill.) Schwer.",
                      "Ocotea porosa var. porosa (Autor1) Autor2",
                      "Ocotea porosa f. porosa",
                      "Ocotea porosa f. porosa Author1",
                      "Euterpe edulis forma edulis",
                      "Euterpe edulis forma edulis Author3"))
```

Output here:
![image](https://github.com/user-attachments/assets/a9b03ed6-6760-40f9-99db-ff9e273387de)

The first row shows a correct example for matters of comparison.

The issue may be in this part of the function since it removes duplicated names

```
  if (length(auth_ids) > 0L) {
    orig_split <- strsplit(res[[1]][auth_ids], " ", fixed = TRUE)
    name_split <- strsplit(res[[2]][auth_ids], " ", fixed = TRUE)
    char_diff <- function(x, y) return(x[!(x %in% y & !duplicated(x))]) #### check here ####
    name_diff <- mapply(char_diff, orig_split, name_split, 
                        SIMPLIFY = FALSE)
```

Cheers!

PS: Ah, yes

below is an example without duplicated epithet + post-rank name

```
> plantR::fixAuthors("Acer saccharum f. glaucum Pax")
```
![image](https://github.com/user-attachments/assets/82e92d05-3287-491d-8bec-f280a56579f4)

Works just fine

**Comment by LimaRAF** [comment]
Thanks @ggrittz for spotting this bug.

It was harder than what I expected to solve this issue, since solving the specific case you reported finally generated problems with other name formats. So, I made more than a few changes in the function (see [this commit](https://github.com/LimaRAF/plantR/commit/0d6722cd8069902ec75251c5034aea8ee756cea5), besides just changing the internal function 'char_diff'). Again, probably not the best solution that could be done to fix the problem at its root, but I am getting similar error ratios as before when benchmarking the function against the WFO backbone. 

But it is not unlikely that I may have generated other bad name editing along the way, so please check it with your dataset to be sure there is no other major and fixable problem in ```fixAuthors()```.

Again, please reinstall ```plantR``` from the 'dev' branch. If all is fine, please let me know so I can close this issue.

**Comment by LimaRAF** [comment]
Still made some improvements in the function and I think that this issue has now been solved. Please look the codes below and let me know if you have any other problems. Closing this issue for now.

```
> plantR::fixAuthors(c("Actinostemon concolor var. microphyllus Müll.Arg.",
+                      "Aesculus glabra var. glabra",
+                      "Comarostaphylis polifolia subsp. polifolia",
+                      "Carya ovata subsp. ovata (Mill.) Schwer.",
+                      "Ocotea porosa var. porosa (Autor1) Autor2",
+                      "Ocotea porosa f. porosa",
+                      "Ocotea porosa f. porosa Author1",
+                      "Euterpe edulis forma edulis",
+                      "Euterpe edulis forma edulis Author3"))
                                          orig.name                                   tax.name      tax.author
1 Actinostemon concolor var. microphyllus Müll.Arg.    Actinostemon concolor var. microphyllus       Müll.Arg.
2                       Aesculus glabra var. glabra                Aesculus glabra var. glabra            <NA>
4        Comarostaphylis polifolia subsp. polifolia Comarostaphylis polifolia subsp. polifolia            <NA>
3          Carya ovata subsp. ovata (Mill.) Schwer.                   Carya ovata subsp. ovata (Mill.) Schwer.
9         Ocotea porosa var. porosa (Autor1) Autor2                  Ocotea porosa var. porosa (Autor1) Autor2
7                           Ocotea porosa f. porosa                    Ocotea porosa f. porosa            <NA>
8                   Ocotea porosa f. porosa Author1                    Ocotea porosa f. porosa         Author1
5                       Euterpe edulis forma edulis                Euterpe edulis forma edulis            <NA>
6               Euterpe edulis forma edulis Author3                Euterpe edulis forma edulis         Author3


```
