### ISSUE TITLE
Error in rspeciesLink

### ISSUE THREAD

**Issue by kvaldemarin** [LimaRAF/plantR#112]
Dear,

I’m encountering an issue with the rspeciesLink function. It is returning the API key error again.

Here’s the code and error message:

```
spp <- c("Eugenia velutifolia", "Eugenia longibracteata")
occs_splink <- rspeciesLink(species = spp, Scope = "plants", basisOfRecord = "PreservedSpecimen", Synonyms = "flora2020")
```

Error in rspeciesLink(species = spp, Scope = "plants", basisOfRecord = "PreservedSpecimen",  : 
  Please provide an API key! Get one at specieslink.net/aut/profile/apikeys

Thanks a lot!

**Comment by LimaRAF** [comment]
Hi @kvaldemarin ,

As mentioned in the error, you need to get your personal API key in the hyperlink mentioned in the error and add it to the ```key``` argument of the function ```rspeciesLink()```. This is now a requirement from them: we can no longer download data without an API key. Please take a look at the help and examples of the function

Let me know if you could fix it so I can close this issue.
