### ISSUE TITLE
Instalalção de dependências e pacotes não mais parte do CRAN

### ISSUE THREAD

**Issue by gaballench** [LimaRAF/plantR#115]
Bom dia,

Tentei instalar o pacote e algumas dependências tem por sua vez dependências externas não documentadas (e.g., `sf`, `lwgeom`).

Seguem os passos que usei para conseguir instalar o pacote usando um ambiente de conda para não ter que lidar com dependências do nível de sistema:

```bash
# criar um ambiente para isolar o pacote dos programas de sistema
conda create -n plantR
conda activate plantR
conda install -c conda-forge r-base r-remotes r-sf r-lwgeom r-curl
```

Já dentro do R:

```r
install.packages("codetools") # evita warnings (code for methods in class...) ao carregar o plantR
remotes::install_github("cran/Taxonstand")
remotes::install_github("LimaRAF/plantR")
```

Abs,

Gustavo

**Comment by LimaRAF** [comment]
Oi Gustavo, 

Estamos fazendo várias alterações e melhorias no pacote, porém no branch de desenvolvimento. Por exemplo, já fizemos a remoção do pacote Taxonstand como dependência do plantR. Sugiro fazer a instalção a partir desse branch e ver se a instalação funciona normalmente.

Att.,
