### ISSUE TITLE
Overall check and optional improvements

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [LimaRAF/plantR#19]
(To be discussed)

## data
- [x] the data sources need to be very well described - where do the gazetteer, the specialist list, etc. come from. 
   - RAFL: will do. 
- [x] checking the gazetteer for Colombia it's clear for me we will need fuzzy greps for this part. the official names of the municipalities do not match what goes in the labels. **this is not the problem**.
  - RAFL: I avoided to use fuzzy greping (for localities or taxonomists) to speed up the process and to avoid any spurous greps. In my opinion, it is safer to continue to complete the gazetter with those exceptions instead of using 'agrep'.
- [x] download functions should have an optional save parameter - even if the default is TRUE
  - RAFL: agreed. it also automatically creates a folder in the local directory, which I think should be optional. But let's see what @saramortara has to say here. AST: I added the optional save yesterday in rocc, I'll bring it here. 

## editing
- [x] `fixFields()` removes optional fields but this maybe should be optional too, even if the default is TRUE - what if the user wants to keep the optional fields for any reason? The warnings could be saved as metadata 
  - RAFL: agreed. @saramortara ?

- [x] `colNumber()` expectations and functioning are not always clear. In the documentation, a "standardized notation" is mentioned, which is this standard notation?
  - RAFL: will do. the stard notation is the argument 'noNumb', which the defaul is "s.n.",

- [x] `fixName()` checks for ampersand and "e". ¿Why doesn't it check for "and", "et", "und", "y"?
  - RAFL: makes sense, will do. Any ideas on how to implement the 'et' for not being consufed with a 'et alli'? 
- [x] in TWDG and maybe other functions that modify names, an initial `tolower()` may be useful to put everything in lower case and then only at the end capitalize - otherwise you have to list everything (Van, van, Der, der) - I tried to make it work but `capName()` does not capitalize initials correctly so I didn't apply any change
   - RAFL: will see what I can do. 
- [x] the separator "," in `TDWGNames()` should not need to have a space. ";" should do the trick. the space should be put internally - **I solved this the wrong way, with a paste0.** 
- [x] `capName()` could be replaced by `stringr::str_to_title()` It works identically but has the same problem as `capName()`, it does not capitalize initials correctly. btw initials are always without space, is this standard mandatory? initials with space work fine in both functions.
   - RAFL: not sure if I understood because the function is not meant to be applied to names and initials, only to names. The initial without spaces is from the old TDWG standard (e.g. 'Lima, R.A.F'). But if there is a function in stingr that does exactly the same, I agree that we should not re-invent the wheel.
   - RAFL [2nd edit]: I double checked the function, made some improvements (e.g. vectorizing) and it is now much faster than before. `stringr::str_to_title()` is still faster but I decided to keep capName() to avoid new depencies. Marked as solved for now.

- [x] Why is `formatName()` executed before TWDGName if it requires TWDG format? Also, it works with first names, not only initials. 
   - RAFL: dont remember anymore: Will check
- [x] in general the ideal standardized outputs should be described because DarwinCore documentation is a nightmare (ironic)
  - RAFL: could you please elaborate a bit more? AST: It's not urgent, I was thinking about having a reference document with the expected outputs. I was thinking about col numbers, since I understood (after writing this) that names will be Lastname, X.X.  
- [x] `getAdmin()` has this error message: "input object needs to have a column loc.correct with the locality strings" this should be explained in the documentation. The fact that the name format must be in this "paraguay_paraguari" way needs to be explicit too. 
  - RAFL: ok, will do. AST: I think I checked it because I did it. 

- [x]  regarding documentation in general not every function needs to be exported, or maybe similar functions can be documented in the same article, so that the person can see their similarities and differences. I am thinking this with all the string formatting inside `formatOcc()`
  - RAFL: think this may be nice for the wrappers and I agree that some functions need not to be exported (e.g. capName). But personally I prefer when each article describe only one function. I have seen many packages doing articles for multiple functions and I personally, I often get lost on which argument and examples correspond to the function I am interested in.

## geographic editing and validation

- [x] `prepLoc()`:  "de la", "del", "du" are missing (lines 37-39)
  - RAFL: yes this need to be done, but first we need to check if the is no problems of creating for two different sites the same string. But yes, I think this shold be done. An if it is done here, we need to adpat the maps and gazetteers. 

- [ ] `prepCoord()`:  possible problems in decimal separator should not happen at this moment but we need an example. I didn't check the math but maybe using package measurements could be a good one
  - RAFL: I took a quick look in function measurements::conv_unit and it looks like it does the trick. But I do not understand why you think problems in decimal separator should not happen at this moment. Remenber that the user my import his own database, so it may have not passed GBIF-like validation steps of the coordinates. 
  - RAFL [2nd edit]: I double checked the function, made some improvements and it now has an example. Everything seems to work. I decided not to use measurements::conv_unit to avoid new depencies. MAked as solved for now.

- [x] the data maps projection and datum is WGS84 but sf does not understand it as 4326. not a huge problem, i think. 
  - RAFL: dont know what happened. will check. Update: checked!

- [x] the decimalDegree transformation will force us to assume that everything is in the same datum (for validation) - for now there will be no projection
  - RAFL: if I remebered it well only problematic coordinates are transformed. Since this should not be the rule, I think the chance of having lots of projection problems is small. And I dont see how we could solve it since projections are rarely provided. Update: marking as solved for now.

**Comment by AndreaSanchezTapia** [comment]
Eu passei um dataframe bem pequeno de coordenadas problemáticas por prepCoord. São dados que vêm de download então: formato impredizível, eu sei. 

24º20'30''S  está sendo parseado como  -0.5000000 e 22º43'58''S  como  -0.9666667. 
O que noto é que quando o S vem depois do 24, ele parsea bem, tipo 23S32'12 > -23.5366667

Outra coisa, quando tem separadores ruins e acaba parecendo milhão, ele não é consistente no parsing, será por espaços invisíveis? mando um print aqui, onde o estranho é que ele faça bem às vezes e às vezes não. 
 
![Captura de Pantalla 2021-05-19 a la(s) 12 23 50](https://user-images.githubusercontent.com/4183062/118872478-752a1300-b89d-11eb-8f87-ef11a6a3be83.png)

boto aqui porque aqui foi que discutimos se prepCoord estava fazendo bem a matemática. Não reabro para não ficar reabrindo. Mando meu mini dataframe aqui, estou testando o parsing das colunas que começam com Verbatim. 

```
format_coord <- readr::read_csv(xxxx)
plantR::prepCoord(data.frame(format_coord),
                    lon = "verbatimLongitude",
                    lat = "verbatimLatitude")

```

[format_coord.csv](https://github.com/LimaRAF/plantR/files/6511171/format_coord.csv)

**Comment by LimaRAF** [comment]
@AndreaSanchezTapia Obrigado pela checagem

Baixei o arquivo que vc mandou e re-testei a função. 

No teste que fiz tá tudo ok:
1) 24º20'30''S -> -24.34167;  22º43'58''S -> -22.73278 ; e 23S32'12 -> -23.5366667. Não sei o que pode ter acontecido aqui.... encoding?
2) Tá ok tb pois a conversão de uma coordenada depende da outra ser válida tb. Adicionei isso nos Details: "Note that if one of the coordinates is valid and the other is not, the function returns NAs for both coordinates."

Me avise se ainda tiver problemas.
