### ISSUE TITLE
Check gazetteer and map

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [LimaRAF/plantR#27]
- [x] Check ADM levels per country (number, names) table
- [x] Check map creation for missing lines and correct order
- [x] Check if the problem is the projection - no more
- [x] Check for missing polygons in GADM and flag manual changes in gazetteer
- [x] Check for mistakes along the way
- [x] Guyane instead of french guiana in country.new?
- [x] The localities in french guiana are weird. Some strings "guyane française" at the end instead of counties (it's not removing that ascii)
- [x] found guyana [guyana] in country.new

From previous issues:
- [ ] in `getAdmin()` you say Argentinean subdivisions are Province instead of State (OK) and Department instead of Municipality, but Department exists _between_ the level of Province and Municipality  (municipality exists) we should check this (for all countries aliás).
- [x] I'm getting a lot of county-level checks errors and thought that it was between countries, but even for brazil we are having these problems. I will split this problem to another issue. 
  - RAFL: class 'check_local.2municip' should be high because all non-NAs locality fields are taken as having an original resolution at locality level, and the majority of the localities are not in the gazetteer. 'check_municip2state' or 'check_municip2country' are more problematic. It can be typos or problems in the strucutre or complitude of the gazetteer. I would create a new issue only about this as well.

**Comment by LimaRAF** [comment]
@AndreaSanchezTapia faltam algumas coisas sobre o gazetter e o cruzamento com os mapas (resolução GADM disponivel). Mas podemos abrir um issue específico posteriormente. Fechando por agora...
