### ISSUE TITLE
keep.cols in checkCoord should be TRUE/FALSE

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [LimaRAF/plantR#48]
We just want to have country/state/county/municipality check columns without them being merged into one.

**Comment by LimaRAF** [comment]
Oi @AndreaSanchezTapia,

Estou fechando esse issue por falta de um decisão nossa sobre se essa questão é um problema ainda e como resolvê-la. Se você achar necessário, pode fazer as modificações necessárias no código ou re-abrir essa issue.
