### ISSUE TITLE
country names in objects and formats should follow the standard nomenclature in other packages

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [LimaRAF/plantR#53]
The user doesn't have a way to know we force things like timor leste or south korea. We should be the ones following current conventions. 
This breaks shares_borders using world or spData, either way this should be controlled. Ex. "cote d'ivoire" is returned as "cote ivoire". The apostrophe is ascii so I don't see the necessity to remove it and on the contrary, it breaks things.

Actually _we should return standard country names in our objects_, that can be recognized by other packages. Either country_codes standards or spData standards. communication will be way easier.

**Comment by LimaRAF** [comment]
Solved with new map world and updates to replaceNames. Closing for now.
