### ISSUE TITLE
error in validateCoord

### ISSUE THREAD

**Issue by lzinger** [LimaRAF/plantR#57]
I get this error when running the command below from the package vignette:
occs <- validateCoord(occs)
Error in `$<-.data.frame`(`*tmp*`, "tmp.order", value = 1:0) : 
  replacement has 2 rows, data has 0

**Comment by LimaRAF** [comment]
This error should be now fixed with commits 87494f8880d919d1935835b4ac435b99c295bd64 and bf6a4917ceade43add7b15a0956bd7f1dd9a2dd6. Closing this issue for now
