### ISSUE TITLE
fixSpecies error

### ISSUE THREAD

**Issue by botanica-furb** [LimaRAF/plantR#66]
without gbif data:

Error in check$species_status[id_authors & !is.na(check$species_status)] <- paste(check$species_status[id_authors &  : 
  NAs não são permitidos em atribuições por subscritos
Além disso: Warning messages:
1: In `[<-.factor`(`*tmp*`, prob.ids, value = c("Blechnum polypodioides f. maius",  :
  invalid factor level, NA generated
2: In `[<-.factor`(`*tmp*`, !prob.ids, value = c("Telmatoblechnum serrulatum",  :
  invalid factor level, NA generated

**Comment by LimaRAF** [comment]
Oi André @botanica-furb ,

Usei os códigos abaixo (os mesmos da vinheta de atualização de duplicatas, até a parte de edição taxonômica) e não consegui reproduzir o erro que vc postou aqui. Talvez seja uma diferença de versões. Por favor, instale o branch de desenvolvimento que estamos usando para garantir que temos a mesma versão e tente novamente. Use primeiro os códigos abaixo literalmente e depois veja se funciona tb no seu código adaptado. Se ainda tiver erro no falamos e tentamos nos aprofundar melhor no problema.

Se não tiver mais o problema me avise tb para podermos fechar esse issue ok?

Para instalar a versão de desevolvimento use o seguinte código (não testei aqui, mas deve funcionar por aí):
```
remotes::install_github("LimaRAF/plantR", ref = "dev", force = TRUE)
```

Código que usei para testar fixSpecies/formatTax:
```
familia <- "Blechnaceae"
occs_splink <- rspeciesLink(family = familia)
occs_gbif <- rgbif2(species = familia, 
                    country = "BR",
                    n.records = 450000)
occs <- formatDwc(splink_data = occs_splink,
                  gbif_data = occs_gbif, drop = TRUE)
occs <- formatOcc(occs)
occs <- formatLoc(occs)
occs <- formatCoord(occs)
head(fixSpecies(occs))
head(formatTax(occs, db = "fbo"))
```

**Comment by LimaRAF** [comment]
Oi André @botanica-furb , se ao testar os códigos acima der tudo certo, por favor, nos avise para que possamos fechar esse issue ok? Valeu!

**Comment by botanica-furb** [comment]
funcionou!
