### ISSUE TITLE
Erro checkCoord

### ISSUE THREAD

**Issue by Thiieres** [LimaRAF/plantR#80]
Estou tentando utilizar esta função seguindo exatamente o que está no tutorial e estou recebendo um erro.
Não tive nenhum erro nas etapas anteriores, só neste momento, com esta função.
Instalei há menos de um dia o pacote, então creio que está atualizado.

> occs <- checkCoord(occs,
+                    keep.cols = c("geo.check", "NAME_0", "country.gazet"))

Error in s2_geography_from_wkb(x, oriented = oriented, check = check) : 
  Evaluation error: Found 1 feature with invalid spherical geometry.
[194] Loop 2 edge 8 crosses loop 3 edge 0.

**Comment by LimaRAF** [comment]
Olá @Thiieres,

Esse é um erro está ligado à uma nova maneira do pacote sf lidar com suas projeções (veja discussão [aqui](https://github.com/r-spatial/sf/issues/1649)). Acabei de rodar o tutorial por aqui e não consegui reproduzir o seu erro, o que talvez queira dizer que o problema não venha do plantR, mas sim de alguma versão de outro pacote.

Minhas sugestões:
- instale/atualize para as ultimas versões dos pacotes `sf` e `s2` e veja se resolve;
- se não, tente "desligar" o uso deste tipo de projeção antes de usar o plantR (ou só checkCoord / validateCoord), usando: `sf::sf_use_s2(FALSE)`
- nós fizemos recentemente modificações nas funções do pacote ligadas à validação de coordenadas. Não acho que esse seja a origem do seu problema, mas vc pode também instalar a versão em desenvolvimento do pacote (a que eu usei para tester o tutorial), caso as demais opções acima não funcionem. Para isso, use o argumento ref: `remotes::install_github("LimaRAF/plantR", ref = "dev")`

De qualquer forma, de um retorno para nós se o problema foi resolvido ou não.

**Comment by LimaRAF** [comment]
Olá @Thiieres,

Novas alterações foram feitas às funções e objetos do pacotes referentes a esse erro que você nos reportou (veja a discussão [nesse issue](https://github.com/LimaRAF/plantR/issues/79#issuecomment-961266823)).

A princípio não deve haver mais problema, mas você terá de re-instalar o pacote a partir do branch `dev`, como lhe havia sugerido anteriormente. Então, estou fechando esse issue. Por favor, nos avise caso encontre mais problemas.
