### ISSUE TITLE
Error in validateCoord()

### ISSUE THREAD

**Issue by WevertonBio** [LimaRAF/plantR#91]
Oi Renato,

Estou tendo um problema recorrente, possivelmente ligado ao issue #79.

Ao tentar rodar a função validateCoord(), obtenho o erro:
```
occ <- validateCoord(df, output = "new.col")

Error in `$<-.data.frame`(`*tmp*`, "geo.check", value = c("ok_state",  : 
  replacement has 2 rows, data has 3
```
As vezes o erro dá com ok_state, em outros casos com ok_county. Imagino que seja por algum problema de projeção, onde 2 locais são atribuídos para um único ponto. Tentei adicionar o comando sf::sf_use_s2(F) antes de validateCoord, mas não resolveu.

Estou usando a versão 0.1.5 do plantR e a versão 1.0-8 do sf.

Estou te mandando as linhas de uma das planilhas que está dando esse erro:
[ErrorValidateCoord.csv](https://github.com/LimaRAF/plantR/files/9105181/ErrorValidateCoord.csv)

**Comment by MonicaCupertino** [comment]
Olá @WevertonBio e @LimaRAF , também estou encontrando um erro na função validateCoord():

> occs <- validateCoord(occs)
Error in if (any(check_these)) { : missing value where TRUE/FALSE needed
>

**Comment by MonicaCupertino** [comment]
Erro resolvido depois que carreguei o pacote geodist!

**Comment by LimaRAF** [comment]
Hi @WevertonBio,

This is related to some problems from the original shapefiles (GADM) that I could not isolate and fix (may also be a consequence of dowgrading the resolution of the original maps...). It meas that for some specific parts of the world a single coordinate can intersect with two different polygons.

I included a work around that should have fixed the problem. Please check the changes related to the commit recently pushed to the dev branch of the package.

If you still run into this error please let me know.
